### ISSUE TITLE
Ability to move computer account to specified OU

### ISSUE THREAD

**Issue by jhsubscribe** [TAMUArch/cookbook.windows_ad#65]
My reading of the Computer :move action is that this is the function one would use to ensure that a computer account is in the correct OU.

":move: Rename a computer object without moving it in the directory tree, or move an object from its current location in the directory to a new location within a single domain controller."

I couldn't get it to work (e.g. it seemed to use the supplied OU as current location) so replaced it with this slightly messy ruby_block for now.   

```
  new_ou = "OU/subOU/subOU"
  domain_pass = "xxxxxxxxx"
  domain_user = "user"
  domain = "corp.acme.com"

 ruby_block "Move OU" do
    block do
      cmd = "dsquery computer -name \"#{node['hostname']}\""
      # pp cmd
      current_dn = CmdHelper.shell_out(cmd, domain_user, domain_pass, domain).stdout.strip
      cmd = "dsmove "
      cmd << current_dn
      cmd << " -newparent "
      cmd << CmdHelper.ou_partial_dn(new_ou) << ',' << CmdHelper.dc_partial_dn(domain)
      # pp cmd
      CmdHelper.shell_out(cmd, domain_user, domain_pass, domain)
    end
  end
```

Unless I'm confused, I figure the options are:
1) Leave as is, no one else needs to move OUs
2) Update this code to include the rename option and push it into the provider
3) Other suggestions

I'm not sure if I'll get time to PR this but just wanted to upload the code so at least others can use it if useful.

**Comment by derekgroh** [comment]
@jhsubscribe Looking back through issues and pull requests.  The dsmove command information was taken directly from the Microsoft Technet on the command https://technet.microsoft.com/en-us/library/cc731094.aspx.  As the provider is written now the method would be:

`
windows_ad_computer 'cn=Workstation,ou=computers,dc=contoso,dc=com' do
  options ({ "newparent' => 'cn=Workstation,ou=pcs,dc=contoso,dc=com' })
end
`

That is a section that is lacking details and examples and seems to require a bit deeper understanding of the command in order to make the provider behave correctly.

We can create a new provider as you suggest that uses the dsmove command, but is formatted specifically to move objects or create an attribute that adds the -newparent parameter.  Open to input on which you feel is easier to understand.

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository. Please reply if you still wish for this to be worked on.
