### ISSUE TITLE
default.rb

### ISSUE THREAD

**Issue by chlsmith** [TAMUArch/cookbook.windows_ad#84]
All the stuff you have added in default.rb is great if you're building a domain controller, but if you're just joining a Windows 2012 R2 server to the domain, it's unnecessary.    You may want to split that out to a separate recipe or something.

**Comment by derekgroh** [comment]
@chlsmith Could you please clarify the issue you are trying to raise?

The primary purpose of this cookbook is to handle managing active directory, with focus on the domain controllers, as such those roles and features are required in order to create a DC.

As the computer provider does not require or include the default recipe I'm confused to the purpose of your request or how the contents of the `default.rb` need edit.  

Perhaps submit a PR indicating what you are thinking for us to review?

**Comment by jdgoins** [comment]
@derekgroh I believe he is referring to the fact that you cannot have a node join the domain without running the default recipe. The computer resource's join domain function seems to rely on dsquery which is not on a Windows system by default.

Example input:
```
windows_ad_computer test.com do
  action :join
  domain_pass 'password'
  domain_user 'test'
  domain_name test.com
  ou Accounts/test_ou
  restart false
end
```

Error:
 ```
================================================================================
 Error executing action `join` on resource 'windows_ad_computer[test.com]'
 ================================================================================

 RuntimeError
 ------------
 Failed to execute command.
 STDOUT:
 STDERR: 'dsquery' is not recognized as an internal or external command,
 operable program or batch file.
```

**Comment by derekgroh** [comment]
We're taking some effort to clean up older issues for this repository.

This feature has been addressed by Chef with the resource: https://docs.chef.io/resource_windows_ad_join.html
